# Generated by Django 5.2.3 on 2025-07-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('SELLER', 'seller'), ('CUSTOMER', 'customer')], default='CUSTOMER', max_length=20),
        ),
    ]
