# Generated by Django 5.2.3 on 2025-07-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_seller_applicant',
            field=models.BooleanField(default=False),
        ),
    ]
